// Mocks generated by Mockito 5.4.6 from annotations
// in fudo_challenge/test/features/posts/domain/usecases/get_posts_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:fudo_challenge/core/exceptions/fudo_exception.dart' as _i5;
import 'package:fudo_challenge/features/posts/domain/entities/post.dart' as _i6;
import 'package:fudo_challenge/features/posts/domain/repository/posts_repository.dart'
    as _i2;
import 'package:fudo_challenge/features/users/domain/entities/user.dart' as _i9;
import 'package:fudo_challenge/features/users/domain/repository/users_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostsRepository extends _i1.Mock implements _i2.PostsRepository {
  MockPostsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.FudoException, List<_i6.Post>>> getPosts({
    int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#userId: userId}),
            returnValue:
                _i3.Future<_i4.Either<_i5.FudoException, List<_i6.Post>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.FudoException, List<_i6.Post>>>(
                    this,
                    Invocation.method(#getPosts, [], {#userId: userId}),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.FudoException, List<_i6.Post>>>);

  @override
  _i3.Future<_i4.Either<_i5.FudoException, _i6.Post>> createPost({
    required String? title,
    required String? body,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #title: title,
              #body: body,
              #userId: userId,
            }),
            returnValue:
                _i3.Future<_i4.Either<_i5.FudoException, _i6.Post>>.value(
                  _i7.dummyValue<_i4.Either<_i5.FudoException, _i6.Post>>(
                    this,
                    Invocation.method(#createPost, [], {
                      #title: title,
                      #body: body,
                      #userId: userId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.FudoException, _i6.Post>>);
}

/// A class which mocks [UsersRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersRepository extends _i1.Mock implements _i8.UsersRepository {
  MockUsersRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.FudoException, List<_i9.User>>> getUsers({
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {#name: name}),
            returnValue:
                _i3.Future<_i4.Either<_i5.FudoException, List<_i9.User>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.FudoException, List<_i9.User>>>(
                    this,
                    Invocation.method(#getUsers, [], {#name: name}),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.FudoException, List<_i9.User>>>);
}
