// Mocks generated by Mockito 5.4.6 from annotations
// in fudo_challenge/test/features/auth/domain/usecases/check_session_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:fudo_challenge/core/common/models/session.dart' as _i8;
import 'package:fudo_challenge/core/exceptions/fudo_exception.dart' as _i5;
import 'package:fudo_challenge/features/auth/domain/entities/auth_user.dart'
    as _i6;
import 'package:fudo_challenge/features/auth/domain/repository/auth_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.FudoException, _i6.AuthUser>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue:
                _i3.Future<_i4.Either<_i5.FudoException, _i6.AuthUser>>.value(
                  _i7.dummyValue<_i4.Either<_i5.FudoException, _i6.AuthUser>>(
                    this,
                    Invocation.method(#login, [email, password]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.FudoException, _i6.AuthUser>>);

  @override
  _i3.Future<_i4.Either<_i5.FudoException, _i8.Session?>> checkSession() =>
      (super.noSuchMethod(
            Invocation.method(#checkSession, []),
            returnValue:
                _i3.Future<_i4.Either<_i5.FudoException, _i8.Session?>>.value(
                  _i7.dummyValue<_i4.Either<_i5.FudoException, _i8.Session?>>(
                    this,
                    Invocation.method(#checkSession, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.FudoException, _i8.Session?>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
